name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Bash it !
      run: bash
    - name: Here we go
      run: timeout 5m bash test.sh
